
import re
import subprocess
import rasterio
import xarray as xr
import rioxarray as rxr
import numpy as np
import pandas as pd

from glob import glob
from itertools import product
from rasterio.enums import Resampling
from tqdm.auto import tqdm
from joblib import Parallel, delayed

from tools.raster import reproject_and_fill



###############################################################################################
#                                  Global variables                                           #
###############################################################################################

NLUM = rxr.open_rasterio('N:/Data-Master/National_Landuse_Map/NLUM_2010-11_mask.tif').squeeze('band').drop_vars('band').astype('uint8')
NLUM_zero = NLUM.copy() * 0


# Paths
SNES_ECNES_dir = 'N:/Data-Master/Biodiversity/DCCEEW/SNES_ECNES'

# Path to the Zonation executable
zonation_exe = 'C:/Program Files (x86)/Zonation5/z5.exe'


# Upstream data
lumap = pd.read_hdf(
    'N:/Data-Master/LUTO_2.0_input_data/Input_data/2D_Spatial_Snapshot/cell_LU_mapping.h5',
    key = 'cell_LU_mapping',
    columns=['LU_DESC','LU_ID_LUTO']
)


# Get the index of cells that are inside the LUTO study area
idx_in_LUTO = np.logical_not(np.isin(lumap['LU_DESC'], ['Non-agricultural land']))  # shape=6956407, sum=4218733

idx_in_LUTO_2D = NLUM_zero.copy()
np.place(idx_in_LUTO_2D.values, NLUM.values, idx_in_LUTO.astype('uint8'))


# Reference raster metadata, matching the GeoTIFFs written by script 5_1
ref_meta = {
    'driver': 'GTiff',
    'dtype': 'uint8',
    'nodata': 255,
    'width': NLUM.rio.width,
    'height': NLUM.rio.height,
    'count': 1,
    'crs': NLUM.rio.crs,
    'transform': NLUM.rio.transform(),
    'compress': 'lzw',
}
ref_meta_float = {**ref_meta, 'dtype': 'float32', 'nodata': np.nan}




# ------------------- Apply Zonation algorithm to merged data ------------------------------------------
'''
The Zonation layer (i.e., the "Suitability" layer) is generated by Carla using the Zonation software at 
'N:/Data-Master/Biodiversity/Environmental-suitability'. 

Here we apply the Zonation algorithm following Carla's method and specifications, but using the weighted 
SNES and ECNES data generated in script 5_1. 

- method: CAZMAX. 
- hierarchical mask: zone_hierarchy.tif; This mask is used to ensure that the Zonation algorithm prioritizes 
  areas within the LUTO study area, while still considering the surrounding regions.
- analysis area mask: zone_mask.tif; This mask is used to define the spatial extent of the analysis, ensuring
  that the Zonation algorithm only considers areas within the LUTO study area.

'''

# Save weighted SNES and ECNES data to GeoTIFFs for Zonation input
SNES_arr_weighted = xr.open_dataarray(f'{SNES_ECNES_dir}/Processed/bio_DCCEEW_SNES_weighted.nc', chunks={})
ECNES_arr_weighted = xr.open_dataarray(f'{SNES_ECNES_dir}/Processed/bio_DCCEEW_ECNES_weighted.nc', chunks={})

xy = np.nonzero(NLUM.values)
def _save_weighted_tif(data_array, species, presence, out_dir, subdir, meta):
    arr_2D = np.full((meta['height'], meta['width']), np.nan, dtype=np.float32)
    arr_2D[xy] = data_array.sel(species=species, presence=presence).values
    safe_name = re.sub(r'[^a-zA-Z0-9]', '_', species)
    save_path = f'{out_dir}/Processed/SNES_ECNES_WEIGHTED/{subdir}/{safe_name}_{presence}.tif'
    with rasterio.open(save_path, 'w', **meta) as dst:
        dst.write(arr_2D, 1)

_weighted_tasks = [
    delayed(_save_weighted_tif)(da, species, presence, SNES_ECNES_dir, subdir, ref_meta_float)
    for da, subdir in ((SNES_arr_weighted, 'SNES'), (ECNES_arr_weighted, 'ECNES'))
    for species, presence in product(da['species'].values, da['presence'].values)
]

for _ in tqdm(Parallel(n_jobs=-1, return_as='generator')(_weighted_tasks), total=len(_weighted_tasks)):
    pass



# Collect the TIF paths for the LIKELY and MAYBE layers for SNES and ECNES, and save to txt files for Zonation input
snes_likely_tifs =      glob(f'{SNES_ECNES_dir}/Processed/SNES_ECNES_WEIGHTED/SNES/*_LIKELY.tif')
ecnes_likely_tifs =     glob(f'{SNES_ECNES_dir}/Processed/SNES_ECNES_WEIGHTED/ECNES/*_LIKELY.tif')
snes_likely_may_tifs =  glob(f'{SNES_ECNES_dir}/Processed/SNES_ECNES_WEIGHTED/SNES/*_LIKELY_AND_MAYBE.tif')
ecnes_likely_may_tifs = glob(f'{SNES_ECNES_dir}/Processed/SNES_ECNES_WEIGHTED/ECNES/*_LIKELY_AND_MAYBE.tif')
mnes_likely_tifs = snes_likely_tifs + ecnes_likely_tifs
mnes_likely_may_tifs = snes_likely_may_tifs + ecnes_likely_may_tifs


# Save the TIF path to txt files
with open(f'{SNES_ECNES_dir}/Processed/Zonation/SNES_likely_files.txt', 'w') as f_snes_likely,\
     open(f'{SNES_ECNES_dir}/Processed/Zonation/ECNES_likely_files.txt', 'w') as f_ecnes_likely,\
     open(f'{SNES_ECNES_dir}/Processed/Zonation/SNES_likely_may_files.txt', 'w') as f_snes_likely_may,\
     open(f'{SNES_ECNES_dir}/Processed/Zonation/ECNES_likely_may_files.txt', 'w') as f_ecnes_likely_may,\
     open(f'{SNES_ECNES_dir}/Processed/Zonation/MNES_likely_files.txt', 'w') as f_mnes_likely,\
     open(f'{SNES_ECNES_dir}/Processed/Zonation/MNES_likely_may_files.txt', 'w') as f_mnes_likely_may:

    f_snes_likely.write('filename\n')
    f_snes_likely.write('\n'.join(f'"{p}"' for p in snes_likely_tifs))
    f_ecnes_likely.write('filename\n')
    f_ecnes_likely.write('\n'.join(f'"{p}"' for p in ecnes_likely_tifs))
    f_snes_likely_may.write('filename\n')
    f_snes_likely_may.write('\n'.join(f'"{p}"' for p in snes_likely_may_tifs))
    f_ecnes_likely_may.write('filename\n')
    f_ecnes_likely_may.write('\n'.join(f'"{p}"' for p in ecnes_likely_may_tifs))
    f_mnes_likely.write('filename\n')
    f_mnes_likely.write('\n'.join(f'"{p}"' for p in mnes_likely_tifs))
    f_mnes_likely_may.write('filename\n')
    f_mnes_likely_may.write('\n'.join(f'"{p}"' for p in mnes_likely_may_tifs))


# Create mask and hierarchy TIF
with rasterio.open(snes_likely_may_tifs[0]) as src:
    meta = src.meta.copy()
    meta.update({
        'dtype': 'uint8',
        'nodata': 0,
        'compress': 'lzw',
        'count': 1,
        'width': NLUM.rio.width,
        'height': NLUM.rio.height,
        'transform': NLUM.rio.transform(),
    })

    zone_mask = NLUM.values.astype('uint8')
    zone_hierarchy = ((zone_mask == 1) * (idx_in_LUTO_2D == 0)).astype('uint8')

    with rasterio.open(f'{SNES_ECNES_dir}/Processed/Zonation/zone_hierarchy.tif', 'w', **meta) as zone_hierarchy_dst,\
         rasterio.open(f'{SNES_ECNES_dir}/Processed/Zonation/zone_mask.tif', 'w', **meta) as zone_mask_dst:
        zone_hierarchy_dst.write(zone_hierarchy, 1)
        zone_mask_dst.write(zone_mask, 1)


# Create the zonation settings file
with open(f'{SNES_ECNES_dir}/Processed/Zonation/snes_likely_settings.txt', 'w') as snes_likely_settings,\
     open(f'{SNES_ECNES_dir}/Processed/Zonation/ecnes_likely_settings.txt', 'w') as ecnes_likely_settings,\
     open(f'{SNES_ECNES_dir}/Processed/Zonation/snes_likely_may_settings.txt', 'w') as snes_likely_may_settings,\
     open(f'{SNES_ECNES_dir}/Processed/Zonation/ecnes_likely_may_settings.txt', 'w') as ecnes_likely_may_settings,\
     open(f'{SNES_ECNES_dir}/Processed/Zonation/mnes_likely_settings.txt', 'w') as mnes_likely_settings,\
     open(f'{SNES_ECNES_dir}/Processed/Zonation/mnes_likely_may_settings.txt', 'w') as mnes_likely_may_settings:

    snes_likely_settings.write((
        f'feature list file = {SNES_ECNES_dir}/Processed/Zonation/SNES_likely_files.txt\n'
        f'analysis area mask layer = {SNES_ECNES_dir}/Processed/Zonation/zone_mask.tif\n'
        f'hierarchic mask layer = {SNES_ECNES_dir}/Processed/Zonation/zone_hierarchy.tif\n'
    ))

    ecnes_likely_settings.write((
        f'feature list file = {SNES_ECNES_dir}/Processed/Zonation/ECNES_likely_files.txt\n'
        f'analysis area mask layer = {SNES_ECNES_dir}/Processed/Zonation/zone_mask.tif\n'
        f'hierarchic mask layer = {SNES_ECNES_dir}/Processed/Zonation/zone_hierarchy.tif\n'
    ))

    snes_likely_may_settings.write((
        f'feature list file = {SNES_ECNES_dir}/Processed/Zonation/SNES_likely_may_files.txt\n'
        f'analysis area mask layer = {SNES_ECNES_dir}/Processed/Zonation/zone_mask.tif\n'
        f'hierarchic mask layer = {SNES_ECNES_dir}/Processed/Zonation/zone_hierarchy.tif\n'
    ))

    ecnes_likely_may_settings.write((
        f'feature list file = {SNES_ECNES_dir}/Processed/Zonation/ECNES_likely_may_files.txt\n'
        f'analysis area mask layer = {SNES_ECNES_dir}/Processed/Zonation/zone_mask.tif\n'
        f'hierarchic mask layer = {SNES_ECNES_dir}/Processed/Zonation/zone_hierarchy.tif\n'
    ))

    mnes_likely_settings.write((
        f'feature list file = {SNES_ECNES_dir}/Processed/Zonation/MNES_likely_files.txt\n'
        f'analysis area mask layer = {SNES_ECNES_dir}/Processed/Zonation/zone_mask.tif\n'
        f'hierarchic mask layer = {SNES_ECNES_dir}/Processed/Zonation/zone_hierarchy.tif\n'
    ))

    mnes_likely_may_settings.write((
        f'feature list file = {SNES_ECNES_dir}/Processed/Zonation/MNES_likely_may_files.txt\n'
        f'analysis area mask layer = {SNES_ECNES_dir}/Processed/Zonation/zone_mask.tif\n'
        f'hierarchic mask layer = {SNES_ECNES_dir}/Processed/Zonation/zone_hierarchy.tif\n'
    ))



# Execute zonation in parallel
zonation_runs = [
    ('snes_likely_settings.txt',     'SNES_likely_Priority'),
    ('ecnes_likely_settings.txt',    'ECNES_likely_Priority'),
    ('snes_likely_may_settings.txt', 'SNES_likely_may_Priority'),
    ('ecnes_likely_may_settings.txt','ECNES_likely_may_Priority'),
    ('mnes_likely_settings.txt',     'MNES_likely_Priority'),
    ('mnes_likely_may_settings.txt', 'MNES_likely_may_Priority'),
]

zonation_procs = [
    subprocess.Popen([
        zonation_exe, '--mode=CAZMAX', '-ah',
        f'{SNES_ECNES_dir}/Processed/Zonation/{settings}',
        f'{SNES_ECNES_dir}/Processed/Zonation/{output}'
    ]) for settings, output in zonation_runs
]

for proc, (settings, _) in zip(zonation_procs, zonation_runs):
    rc = proc.wait()
    if rc != 0:
        print(f'WARNING: Zonation failed for {settings} (exit code {rc})')


# Merge all zonation layers and save as NetCDF
zonation_layers = {
    'ECNES_likely_may': f'{SNES_ECNES_dir}/Processed/Zonation/ECNES_likely_may_Priority/rankmap.tif',
    'ECNES_likely': f'{SNES_ECNES_dir}/Processed/Zonation/ECNES_likely_Priority/rankmap.tif',
    'SNES_likely_may': f'{SNES_ECNES_dir}/Processed/Zonation/SNES_likely_may_Priority/rankmap.tif',
    'SNES_likely': f'{SNES_ECNES_dir}/Processed/Zonation/SNES_likely_Priority/rankmap.tif',
    'MNES_likely_may': f'{SNES_ECNES_dir}/Processed/Zonation/MNES_likely_may_Priority/rankmap.tif',
    'MNES_likely': f'{SNES_ECNES_dir}/Processed/Zonation/MNES_likely_Priority/rankmap.tif',
}

zonation_arr = xr.DataArray(
    np.zeros((len(zonation_layers), NLUM.sum().item()), dtype=np.float32),
    dims=['layer', 'cell'],
    coords={'layer':list(zonation_layers.keys()), 'cell':np.arange(NLUM.sum().item())}
)

for layer, path in zonation_layers.items():
    with rasterio.open(path) as src:
        arr = src.read(1)
        arr = arr[np.nonzero(NLUM.values)]
        zonation_arr.loc[dict(layer=layer)] = arr


# Save to nc
zonation_arr.name = 'data'
zonation_arr.to_netcdf(
    f'{SNES_ECNES_dir}/Processed/bio_NES_Zonation.nc',
    mode='w',
    encoding={'data': {
        "compression": "gzip",
        "compression_opts": 5,
        "dtype": 'float32'
        },
    },
    engine='h5netcdf'
)



# ------------------- Get Zonation layer for RHI (Relative Habitat Importance) ------------------------------------------
'''
RHI is a finished product. DCCEEW has already run the Zonation 5 prioritisation (CAZMAX over the SNES
'likely to occur' SDMs) and published the ranked 0-100 raster at 1 km. No Zonation run is needed here —
this section only normalises that raster to the LUTO spatial format (NLUM extent, resolution and cell
alignment).

Source:  https://fed.dcceew.gov.au/datasets/0732222780f84f9387975f26e0bc5af6/about
Provided by Patrick @ ClimateWorks; saved by Jinzhu 20260803.
'''


RHI_dir = 'N:/Data-Master/Biodiversity/DCCEEW/RHI (Relative Habitat Importance)'
RHI_path = f'{RHI_dir}/Relative Habitat Importance/relative_habitat_importance.tif'

RHI_ly = rxr.open_rasterio(RHI_path)

# RHI already shares the NLUM CRS (EPSG:4283) and 0.01-degree resolution, but its grid origin is
# offset by a fraction of a cell (-0.35 in x, 0.46 in y), so a reproject_match is still needed.
# Nearest keeps the 0-100 values as discrete ranks; bilinear would blend them into values that are
# no longer ranks.
#
# to_fill=-1 is a sentinel that never occurs in RHI, so the nearest-fill step is a deliberate no-op.
# DCCEEW uses 0 for 'not ranked' — 78,704 NLUM cells (1.1%), mostly islands outside the GEODATA COAST
# 100K extent their analysis was clipped to — and the default to_fill=0 would overwrite those with a
# neighbour's rank. Keeping them at 0 means no cell carries a rank DCCEEW did not assign it.
RHI_match = reproject_and_fill(RHI_ly, NLUM, NLUM.astype(bool), to_fill=-1, resampling=Resampling.nearest)

RHI_match.rio.to_raster(f'{RHI_dir}/bio_DCCEEW_RHI.tif', compress='lzw', dtype='float32', nodata=np.nan)

RHI_arr = xr.DataArray(
    RHI_match.values[np.nonzero(NLUM.values)].astype(np.float32),
    dims=['cell'],
    coords={'cell': np.arange(NLUM.sum().item())}
)

RHI_arr.name = 'data'
RHI_arr.to_netcdf(
    f'{RHI_dir}/bio_DCCEEW_RHI.nc',
    mode='w',
    encoding={'data': {
        "compression": "gzip",
        "compression_opts": 5,
        "dtype": 'float32'
        },
    },
    engine='h5netcdf'
)



